steps:
  # Build image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west4-docker.pkg.dev/${PROJECT_ID}/firebaseapphosting-images/backend-go:${BUILD_ID}",
        "-f",
        "Dockerfile",
        ".",
      ]

  # Push image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-west4-docker.pkg.dev/${PROJECT_ID}/firebaseapphosting-images/backend-go:${BUILD_ID}",
      ]

images:
  - "europe-west4-docker.pkg.dev/${PROJECT_ID}/firebaseapphosting-images/backend-go:${BUILD_ID}"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
