steps:
  # Step 1: Build the Go binary
  - name: "golang:1.22"
    args: ["go", "build", "-o", "server", "."]
    env:
      - "CGO_ENABLED=0"
      - "GOOS=linux"
      - "GOARCH=amd64"

  # Step 2: Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/go-api:$BUILD_ID", "."]

  # Step 3: Push the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/go-api:$BUILD_ID"]

  # Step 4: Deploy to Cloud Run (Firebase App Hosting uses Cloud Run)
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "go-api"
      - "--image"
      - "gcr.io/$PROJECT_ID/go-api:$BUILD_ID"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

images:
  - "gcr.io/$PROJECT_ID/go-api:$BUILD_ID"

options:
  logging: CLOUD_LOGGING_ONLY
